version: '3.8'

services:
  feature-service:
    build:
      context: .
      dockerfile: feature-service/Dockerfile
    container_name: feature-service
    environment:
      SERVER_NAME: feature-service
      SERVER_PORT: 8080
    ports:
      - "8081:8080"
    networks:
      - monitoring

  toggle-service:
    build:
      context: .
      dockerfile: toggle-service/Dockerfile
    container_name: toggle-service
    environment:
      SERVER_NAME: toggle-service
      SERVER_PORT: 8080
    ports:
      - "8082:8080"
    networks:
      - monitoring

  analytics-service:
    build:
      context: .
      dockerfile: analytics-service/Dockerfile
    container_name: analytics-service
    environment:
      SERVER_NAME: analytics-service
      SERVER_PORT: 8080
    ports:
      - "8083:8080"
    networks:
      - monitoring

  api-gateway:
    build:
      context: .
      dockerfile: api-gateway/Dockerfile
    container_name: api-gateway
    depends_on:
      - feature-service
      - toggle-service
      - analytics-service
    ports:
      - "${SERVER_PORT}:${SERVER_PORT}"
    environment:
      SERVER_PORT: ${SERVER_PORT}
      LOADBALANCER_ALGORITHM: ${LOADBALANCER_ALGORITHM}
      LOADBALANCER_RETRIES: ${LOADBALANCER_RETRIES}
      LOADBALANCER_RETRY_DELAY: ${LOADBALANCER_RETRY_DELAY}
    networks:
      - monitoring

  prometheus:
    image: prom/prometheus
    container_name: prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
    networks:
      - monitoring

  grafana:
    image: grafana/grafana
    container_name: grafana
    ports:
      - "3000:3000"
    networks:
      - monitoring

  discovery-server:
    build:
      context: .
      dockerfile: discovery-server/Dockerfile
    container_name: discovery-server
    ports:
      - "8761:8761"
    networks:
      - monitoring

networks:
  monitoring:
