version: '3.8'

services:
  backend-server-1:
    build: ./backend-server-1
    container_name: backend-server-1
    environment:
      - SERVER_NAME=Backend-1
    ports:
      - "8081:8080"

  backend-server-2:
    build: ./backend-server-2
    container_name: backend-server-2
    environment:
      - SERVER_NAME=Backend-2
    ports:
      - "8082:8080"

  backend-server-3:
    build: ./backend-server-3
    container_name: backend-server-3
    environment:
      - SERVER_NAME=Backend-3
    ports:
      - "8083:8080"

  load-balancer:
    build: ./load-balancer
    container_name: load-balancer
    depends_on:
      - backend-server-1
      - backend-server-2
      - backend-server-3
    ports:
      - "8080:8080"
