resilience4j:
  retry:
    instances:
      load-balancer-retry:
        max-attempts: 3
        wait-duration: 200ms

  circuitbreaker:
    instances:
      toggle-service:
        sliding-window-size: 10
        failure-rate-threshold: 50
      feature-service:
        sliding-window-size: 10
        failure-rate-threshold: 50
      analytics-service:
        sliding-window-size: 10
        failure-rate-threshold: 50

  ratelimiter:
    instances:
      toggle-service:
        limitForPeriod: 5
        limitRefreshPeriod: 10s
        timeoutDuration: 0
      feature-service:
        limitForPeriod: 3
        limitRefreshPeriod: 10s
        timeoutDuration: 0
      analytics-service:
        limitForPeriod: 3
        limitRefreshPeriod: 10s
        timeoutDuration: 0
