global:
  scrape_interval: 5s

scrape_configs:
  - job_name: 'load-balancer'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['load-balancer:8080']

  - job_name: 'backend-servers'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: [ 'backend-server-1:8080' ]
      - targets: [ 'backend-server-2:8080' ]
      - targets: [ 'backend-server-3:8080' ]