server:
  port: 8080

spring:
  application:
    name: analytics-service

eureka:
  client:
    service-url:
      defaultZone: http://discovery-server:8761/eureka
  instance:
    prefer-ip-address: true
