resilience4j:
  retry:
    instances:
      load-balancer-retry:
        max-attempts: 3
        wait-duration: 200ms

  circuitbreaker:
    instances:
      http://backend-server-1:8080/api/test:
        sliding-window-size: 10
        failure-rate-threshold: 50
      http://backend-server-2:8080/api/test:
        sliding-window-size: 10
        failure-rate-threshold: 50
      http://backend-server-3:8080/api/test:
        sliding-window-size: 10
        failure-rate-threshold: 50
